---
title: "comment-utiliser-ce-package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{comment-utiliser-ce-package}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library(ACC) 
library(tidyverse)
```

## Téléchargement des données

```{r}
library(BARIS)
iddonnees <- "53698f4ca3a729239d2036df"
BARIS_explain(iddonnees)
ressources <- BARIS_resources(iddonnees) #Tibble avec les URL
data_2019 <- ressources %>% 
  filter(str_detect(title,"2019"),format=="csv") #On garde les fichiers csv de 2019

if(!dir.exists("data-raw"))
  dir.create("data-raw")

for(i in 1:nrow(data_2019)){
  tmp_df <- data_2019[i,]
  download.file(url = tmp_df$url, 
                destfile = paste0("data-raw/",tmp_df$title),overwrite = T)
}
```

## Insertion des libellés dans la table CARACTERISTIQUES

```{r}
carac <- read.csv("~/Documents/Formation_R/Certificat_Data_Scientist/ACC/data-raw/caracteristiques-2019.csv",sep=";",header=T)
# Ajout des libellés relatifs à la luminosité
carac <- carac %>% 
  mutate(libl_lum=ifelse(lum==1,"Plein jour", 
                         ifelse(lum==2,"Crépuscule ou aube", 
                                ifelse(lum==3,"Nuit sans éclairage public",
                                       ifelse(lum==4,"Nuit avec éclairage public non allumé","Nuit avec éclairage public allumé")
                                       )
                                )
                         )
        ) %>%
# Ajout des libellés relatifs à l'agglomération
  mutate(libl_agg=ifelse(agg==1,"Hors agglomération","En agglomération")) %>%
# Ajout des libellés relatifs aux types d'intersection
  mutate(libl_int=ifelse(int==1,"Hors intersection", 
                         ifelse(int==2,"Intersection en X", 
                                ifelse(int==3,"Intersection en T",
                                       ifelse(int==4,"Intersection en Y",
                                              ifelse(int==5,"Intersection à plus de 4 branches",
                                                     ifelse(int==6,"Giratoire",
                                                            ifelse(int==7,"Place",
                                                                   ifelse(int==8,"Passage à niveau","Autre intersection")
                                                                   )
                                                            )
                                                     )
                                              )
                                      )
                                )
                        )
        ) %>%
# Ajout des libellés relatifs aux conditions atmosphériques
  mutate(libl_atm=ifelse(atm==1,"Normale", 
                         ifelse(atm==2,"Pluie légère", 
                                ifelse(atm==3,"Pluie forte",
                                       ifelse(atm==4,"Neige - grêle",
                                              ifelse(atm==5,"Brouillard - fumée",
                                                     ifelse(atm==6,"Vent fort - tempête",
                                                            ifelse(atm==7,"Temps éblouissant",
                                                                   ifelse(atm==8,"Temps couvert","Autre")
                                                                   )
                                                            )
                                                     )
                                              )
                                      )
                                )
                        )
        )
carac
```

## Insertion des libellés dans la table LIEUX

```{r}
lieux <- read.csv("~/Documents/Formation_R/Certificat_Data_Scientist/ACC/data-raw/lieux-2019.csv",sep=";",header=T)
# Ajout des libellés relatifs à la catégorie de route
lieux <- lieux %>% 
  mutate(libl_catr=ifelse(catr==1,"Autoroute", 
                         ifelse(catr==2,"Route Nationale", 
                                ifelse(catr==3,"Route Départementale",
                                       ifelse(catr==4,"Voie Communale",
                                              ifelse(catr==5,"Hors réseau public",
                                                     ifelse(catr==6,"Parc de stationnement ouvert à la circulation publique","Autre")
                                                     )
                                              )
                                      )
                                )
                        )
        )
lieux
```

