<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Analyses des Correspondances Multiples et Classification sur la base accidents • ACC</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Analyses des Correspondances Multiples et Classification sur la base accidents">
<meta property="og:description" content="ACC">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">ACC</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li class="divider">
    <li class="dropdown-header">Description des données</li>
    <li>
      <a href="../articles/exploration-donnees-brutes.html">Exploration des données brutes</a>
    </li>
    <li>
      <a href="../articles/Stats_Descriptives.html">Statistiques descriptives avec ggplot2</a>
    </li>
    <li class="divider">
    <li class="dropdown-header">Classification</li>
    <li>
      <a href="../articles/ACM_classif.html">Analyses des Correspondances Multiples et Classification sur la base accidents</a>
    </li>
    <li class="divider">
    <li class="dropdown-header">Modélisation</li>
    <li>
      <a href="../articles/modeles.html">Prévisions des accidents ayant entrainés des blessures/décès</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="ACM_classif_files/header-attrs-2.5/header-attrs.js"></script><link href="ACM_classif_files/anchor-sections-1.0/anchor-sections.css" rel="stylesheet">
<script src="ACM_classif_files/anchor-sections-1.0/anchor-sections.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Analyses des Correspondances Multiples et Classification sur la base accidents</h1>
            
      
      
      <div class="hidden name"><code>ACM_classif.Rmd</code></div>

    </div>

    
    
<p>Bibliothèques utiles à l’éxécution du programme</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></code></pre></div>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.4     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.0</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dbplyr.tidyverse.org/">dbplyr</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: le package 'dbplyr' a été compilé avec la version R 4.0.3</code></pre>
<pre><code>## 
## Attachement du package : 'dbplyr'</code></pre>
<pre><code>## The following objects are masked from 'package:dplyr':
## 
##     ident, sql</code></pre>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://factominer.free.fr">FactoMineR</a></span><span class="op">)</span> <span class="co"># pour les ACM</span></code></pre></div>
<pre><code>## Warning: le package 'FactoMineR' a été compilé avec la version R 4.0.3</code></pre>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mclust-org.github.io/mclust/">mclust</a></span><span class="op">)</span> <span class="co"># pour la classification</span></code></pre></div>
<pre><code>## Warning: le package 'mclust' a été compilé avec la version R 4.0.3</code></pre>
<pre><code>## Package 'mclust' version 5.4.7
## Type 'citation("mclust")' for citing this R package in publications.</code></pre>
<pre><code>## 
## Attachement du package : 'mclust'</code></pre>
<pre><code>## The following object is masked from 'package:purrr':
## 
##     map</code></pre>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.statistik.tu-dortmund.de">klaR</a></span><span class="op">)</span> <span class="co"># pour les K-modes</span></code></pre></div>
<pre><code>## Warning: le package 'klaR' a été compilé avec la version R 4.0.4</code></pre>
<pre><code>## Le chargement a nécessité le package : MASS</code></pre>
<pre><code>## 
## Attachement du package : 'MASS'</code></pre>
<pre><code>## The following object is masked from 'package:dplyr':
## 
##     select</code></pre>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">ACC</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Attachement du package : 'ACC'</code></pre>
<pre><code>## The following object is masked from 'package:tidyr':
## 
##     population</code></pre>
<p>Préparation de la base de travail</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"population"</span>, package <span class="op">=</span> <span class="st">"ACC"</span><span class="op">)</span>
<span class="va">accidents2</span> <span class="op">&lt;-</span>  <span class="fu"><a href="../reference/mutate_pour_modele.html">mutate_pour_modele</a></span><span class="op">(</span><span class="va">accidents</span>, <span class="va">population</span><span class="op">)</span></code></pre></div>
<pre><code>## Joining, by = "dep"</code></pre>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Suppression des variables d'identifiants et les variables quantitatives</span>
<span class="va">base</span> <span class="op">&lt;-</span> <span class="va">accidents2</span> <span class="op">%&gt;%</span>
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">Num_Acc</span><span class="op">)</span>

<span class="co"># résumé de la base</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">base</span><span class="op">)</span></code></pre></div>
<pre><code>##      catu               grav               sexe              secu1          
##  Length:480116      Length:480116      Length:480116      Length:480116     
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##      catv               lum                agg                atm           
##  Length:480116      Length:480116      Length:480116      Length:480116     
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##      col            intersection            mois_acc          jour_acc    
##  Length:480116      Length:480116      juin     : 45582   dimanche:58858  
##  Class :character   Class :character   octobre  : 44628   lundi   :64026  
##  Mode  :character   Mode  :character   juillet  : 43731   mardi   :68570  
##                                        septembre: 43429   mercredi:68885  
##                                        novembre : 41484   jeudi   :70085  
##                                        mai      : 41192   vendredi:79923  
##                                        (Other)  :220070   samedi  :69769  
##      catr               circ               prof               plan          
##  Length:480116      Length:480116      Length:480116      Length:480116     
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##      surf              infra               situ              gr_dep         
##  Length:480116      Length:480116      Length:480116      Length:480116     
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##   classe_age          cl_heure        
##  Length:480116      Length:480116     
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
##                                       
## </code></pre>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">base</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "catu"         "grav"         "sexe"         "secu1"        "catv"        
##  [6] "lum"          "agg"          "atm"          "col"          "intersection"
## [11] "mois_acc"     "jour_acc"     "catr"         "circ"         "prof"        
## [16] "plan"         "surf"         "infra"        "situ"         "gr_dep"      
## [21] "classe_age"   "cl_heure"</code></pre>
<div id="etude-1---acm-sur-lensemble-des-variables-qualitatives-de-la-base-de-données" class="section level1">
<h1 class="hasAnchor">
<a href="#etude-1---acm-sur-lensemble-des-variables-qualitatives-de-la-base-de-donn%C3%A9es" class="anchor"></a>Etude 1 - ACM sur l’ensemble des variables qualitatives de la base de données</h1>
<p>Dans cette première ACM, on intègre toutes les variables qualitatives.</p>
<div id="acm" class="section level2">
<h2 class="hasAnchor">
<a href="#acm" class="anchor"></a>ACM</h2>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res.mca</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/FactoMineR/man/MCA.html">MCA</a></span><span class="op">(</span><span class="va">base</span>,
                level.ventil <span class="op">=</span> <span class="fl">0.025</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-3-1.png" width="700"><img src="ACM_classif_files/figure-html/unnamed-chunk-3-2.png" width="700"><img src="ACM_classif_files/figure-html/unnamed-chunk-3-3.png" width="700"></p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># toutes les modalités représentant moins de 2.5 % sont ventilées aléatoirement dans les autres modalités (les tués représentent 2,7 % des accidents, d'où le filtre à 2,5 % car on veut garder la modalité "tué")</span></code></pre></div>
</div>
<div id="réprésentation-graphique-des-poids-des-dimensions" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9pr%C3%A9sentation-graphique-des-poids-des-dimensions" class="anchor"></a>Réprésentation graphique des poids des dimensions</h2>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tableau avec les poids des axes</span>
<span class="va">res.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></code></pre></div>
<pre><code>##        dim 1        dim 2        dim 3        dim 4        dim 5        dim 6 
## 4.318796e+00 3.601444e+00 3.244844e+00 2.971318e+00 2.922702e+00 2.624338e+00 
##        dim 7        dim 8        dim 9       dim 10       dim 11       dim 12 
## 2.331530e+00 2.014529e+00 1.857602e+00 1.760446e+00 1.742006e+00 1.625940e+00 
##       dim 13       dim 14       dim 15       dim 16       dim 17       dim 18 
## 1.616881e+00 1.525197e+00 1.508116e+00 1.480440e+00 1.474238e+00 1.462671e+00 
##       dim 19       dim 20       dim 21       dim 22       dim 23       dim 24 
## 1.442683e+00 1.439111e+00 1.434307e+00 1.430413e+00 1.427490e+00 1.421211e+00 
##       dim 25       dim 26       dim 27       dim 28       dim 29       dim 30 
## 1.416044e+00 1.414128e+00 1.412967e+00 1.410727e+00 1.409436e+00 1.404948e+00 
##       dim 31       dim 32       dim 33       dim 34       dim 35       dim 36 
## 1.404270e+00 1.402420e+00 1.400362e+00 1.394871e+00 1.390997e+00 1.387086e+00 
##       dim 37       dim 38       dim 39       dim 40       dim 41       dim 42 
## 1.380483e+00 1.376480e+00 1.372967e+00 1.359655e+00 1.352260e+00 1.349605e+00 
##       dim 43       dim 44       dim 45       dim 46       dim 47       dim 48 
## 1.327337e+00 1.311908e+00 1.300648e+00 1.257187e+00 1.255473e+00 1.221473e+00 
##       dim 49       dim 50       dim 51       dim 52       dim 53       dim 54 
## 1.200389e+00 1.168240e+00 1.158308e+00 1.148464e+00 1.140000e+00 1.101955e+00 
##       dim 55       dim 56       dim 57       dim 58       dim 59       dim 60 
## 1.056425e+00 1.019237e+00 9.871491e-01 9.727308e-01 9.407933e-01 8.781868e-01 
##       dim 61       dim 62       dim 63       dim 64       dim 65       dim 66 
## 8.569647e-01 7.936616e-01 7.631358e-01 7.165840e-01 6.787478e-01 6.604048e-01 
##       dim 67       dim 68       dim 69       dim 70       dim 71 
## 4.503833e-01 4.112554e-01 3.232286e-01 1.817682e-01 1.804131e-23</code></pre>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Histogramme</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="va">res.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>, names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Dim"</span>, <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">res.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-4-1.png" width="700"></p>
<p>Au vu du coude, on ne garderait que 7 axes. Toutefois, cela représente assez peu (22 %), ce qui est normal en ACM.</p>
</div>
<div id="réprésentation-graphique-des-individus" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9pr%C3%A9sentation-graphique-des-individus" class="anchor"></a>Réprésentation graphique des individus</h2>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res.mca</span>, invisible <span class="op">=</span> <span class="st">"var"</span>,
     title <span class="op">=</span> <span class="st">"Représentation des individus selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-5-1.png" width="700"></p>
<p>Vu le nombre d’individus, aucun intérêt car pas lisible.</p>
</div>
<div id="représentation-graphique-des-modalités-des-variables" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-modalit%C3%A9s-des-variables" class="anchor"></a>Représentation graphique des modalités des variables</h2>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res.mca</span>, invisible <span class="op">=</span> <span class="st">"ind"</span>,
     title <span class="op">=</span> <span class="st">"Représentation des modalités selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-6-1.png" width="700"> Même constat que pour le graphique précédent, trop de modalités et peu lisible.</p>
</div>
<div id="résumé-des-stats-de-lacm" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9sum%C3%A9-des-stats-de-lacm" class="anchor"></a>Résumé des stats de l’ACM</h2>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">res.mca</span>, nbelements<span class="op">=</span><span class="fl">2</span>, <span class="co"># nombre d'individus</span>
        ncp<span class="op">=</span><span class="fl">5</span>, <span class="co"># nombre de dimensions</span>
        nb.dec<span class="op">=</span><span class="fl">2</span><span class="op">)</span> </code></pre></div>
<pre><code>## 
## Call:
## MCA(X = base, level.ventil = 0.025) 
## 
## 
## Eigenvalues
##                       Dim.1  Dim.2  Dim.3  Dim.4  Dim.5  Dim.6  Dim.7  Dim.8
## Variance               0.14   0.12   0.10   0.10   0.09   0.08   0.08   0.07
## % of var.              4.32   3.60   3.24   2.97   2.92   2.62   2.33   2.01
## Cumulative % of var.   4.32   7.92  11.17  14.14  17.06  19.68  22.01  24.03
##                       Dim.9 Dim.10 Dim.11 Dim.12 Dim.13 Dim.14 Dim.15 Dim.16
## Variance               0.06   0.06   0.06   0.05   0.05   0.05   0.05   0.05
## % of var.              1.86   1.76   1.74   1.63   1.62   1.53   1.51   1.48
## Cumulative % of var.  25.89  27.65  29.39  31.02  32.63  34.16  35.67  37.15
##                      Dim.17 Dim.18 Dim.19 Dim.20 Dim.21 Dim.22 Dim.23 Dim.24
## Variance               0.05   0.05   0.05   0.05   0.05   0.05   0.05   0.05
## % of var.              1.47   1.46   1.44   1.44   1.43   1.43   1.43   1.42
## Cumulative % of var.  38.62  40.08  41.53  42.96  44.40  45.83  47.26  48.68
##                      Dim.25 Dim.26 Dim.27 Dim.28 Dim.29 Dim.30 Dim.31 Dim.32
## Variance               0.05   0.05   0.05   0.05   0.05   0.05   0.05   0.05
## % of var.              1.42   1.41   1.41   1.41   1.41   1.40   1.40   1.40
## Cumulative % of var.  50.09  51.51  52.92  54.33  55.74  57.15  58.55  59.95
##                      Dim.33 Dim.34 Dim.35 Dim.36 Dim.37 Dim.38 Dim.39 Dim.40
## Variance               0.05   0.05   0.04   0.04   0.04   0.04   0.04   0.04
## % of var.              1.40   1.39   1.39   1.39   1.38   1.38   1.37   1.36
## Cumulative % of var.  61.35  62.75  64.14  65.53  66.91  68.28  69.66  71.02
##                      Dim.41 Dim.42 Dim.43 Dim.44 Dim.45 Dim.46 Dim.47 Dim.48
## Variance               0.04   0.04   0.04   0.04   0.04   0.04   0.04   0.04
## % of var.              1.35   1.35   1.33   1.31   1.30   1.26   1.26   1.22
## Cumulative % of var.  72.37  73.72  75.05  76.36  77.66  78.92  80.17  81.39
##                      Dim.49 Dim.50 Dim.51 Dim.52 Dim.53 Dim.54 Dim.55 Dim.56
## Variance               0.04   0.04   0.04   0.04   0.04   0.04   0.03   0.03
## % of var.              1.20   1.17   1.16   1.15   1.14   1.10   1.06   1.02
## Cumulative % of var.  82.59  83.76  84.92  86.07  87.21  88.31  89.37  90.39
##                      Dim.57 Dim.58 Dim.59 Dim.60 Dim.61 Dim.62 Dim.63 Dim.64
## Variance               0.03   0.03   0.03   0.03   0.03   0.03   0.02   0.02
## % of var.              0.99   0.97   0.94   0.88   0.86   0.79   0.76   0.72
## Cumulative % of var.  91.37  92.34  93.29  94.16  95.02  95.81  96.58  97.29
##                      Dim.65 Dim.66 Dim.67 Dim.68 Dim.69 Dim.70 Dim.71
## Variance               0.02   0.02   0.01   0.01   0.01   0.01   0.00
## % of var.              0.68   0.66   0.45   0.41   0.32   0.18   0.00
## Cumulative % of var.  97.97  98.63  99.08  99.50  99.82 100.00 100.00
## 
## Individuals (the 2 first)
##                   Dim.1   ctr  cos2   Dim.2   ctr  cos2   Dim.3   ctr  cos2  
## 1               | -0.10  0.00  0.00 |  0.08  0.00  0.00 |  0.30  0.00  0.03 |
## 2               | -0.19  0.00  0.01 | -0.11  0.00  0.00 |  0.06  0.00  0.00 |
##                 Dim.4   ctr  cos2   Dim.5   ctr  cos2  
## 1               -0.41  0.00  0.05 | -0.10  0.00  0.00 |
## 2               -0.35  0.00  0.05 | -0.01  0.00  0.00 |
## 
## Categories (the 2 first)
##                     Dim.1     ctr    cos2  v.test     Dim.2     ctr    cos2
## catu_Conducteur |   -0.08    0.15    0.02  -90.12 |   -0.36    3.77    0.36
## catu_Passager   |   -0.56    1.77    0.07 -177.68 |    0.33    0.75    0.02
##                  v.test     Dim.3     ctr    cos2  v.test     Dim.4     ctr
## catu_Conducteur -418.07 |   -0.09    0.24    0.02 -100.11 |   -0.01    0.00
## catu_Passager    105.61 |    0.30    0.69    0.02   96.16 |    0.00    0.00
##                    cos2  v.test     Dim.5     ctr    cos2  v.test  
## catu_Conducteur    0.00  -10.58 |    0.00    0.00    0.00    3.24 |
## catu_Passager      0.00   -0.37 |    0.18    0.28    0.01   58.02 |
## 
## Categorical variables (eta2)
##                   Dim.1 Dim.2 Dim.3 Dim.4 Dim.5  
## catu            |  0.33  0.60  0.02  0.00  0.02 |
## grav            |  0.06  0.03  0.38  0.06  0.06 |</code></pre>
</div>
</div>
<div id="etude-2---on-regarde-la-gravité-des-blessures-selon-le-profil-des-usagers" class="section level1">
<h1 class="hasAnchor">
<a href="#etude-2---on-regarde-la-gravit%C3%A9-des-blessures-selon-le-profil-des-usagers" class="anchor"></a>Etude 2 - on regarde la gravité des blessures selon le profil des usagers</h1>
<p>Dans cette 2e ACM, on étudie le fait d’être Indemne/Blessé selon les données démographiques des victimes (age, sexe, catégorie d’usagers).</p>
<div id="acm-1" class="section level2">
<h2 class="hasAnchor">
<a href="#acm-1" class="anchor"></a>ACM</h2>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># rq : on ne garde que les variables démographiques (sexe, age, catégorie d'usagers) et les autres sont passées en illustratives</span>
<span class="va">res2.mca</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/FactoMineR/man/MCA.html">MCA</a></span><span class="op">(</span><span class="va">base</span>, quali.sup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span><span class="op">:</span><span class="fl">20</span>,<span class="fl">22</span><span class="op">)</span>, level.ventil <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-8-1.png" width="700"><img src="ACM_classif_files/figure-html/unnamed-chunk-8-2.png" width="700"><img src="ACM_classif_files/figure-html/unnamed-chunk-8-3.png" width="700"></p>
</div>
<div id="réprésentation-graphique-des-poids-des-dimensions-1" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9pr%C3%A9sentation-graphique-des-poids-des-dimensions-1" class="anchor"></a>Réprésentation graphique des poids des dimensions</h2>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tableau avec les poids</span>
<span class="va">res2.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></code></pre></div>
<pre><code>##     dim 1     dim 2     dim 3     dim 4     dim 5     dim 6     dim 7     dim 8 
## 12.494743  9.455093  8.112075  7.871608  7.859098  7.703450  7.692308  7.686830 
##     dim 9    dim 10    dim 11    dim 12    dim 13 
##  7.556638  7.428045  6.499929  5.547357  4.092826</code></pre>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Histogramme</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="va">res2.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>, names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Dim"</span>, <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">res2.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-9-1.png" width="700"></p>
<p>Au vu du graph, on peut garder 2 axes, qui explique 22 %.</p>
</div>
<div id="réprésentation-graphique-des-individus-1" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9pr%C3%A9sentation-graphique-des-individus-1" class="anchor"></a>Réprésentation graphique des individus</h2>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res2.mca</span>, invisible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"var"</span>,<span class="st">"quali.sup"</span><span class="op">)</span>,
     title <span class="op">=</span> <span class="st">"Représentation des individus selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-10-1.png" width="700"></p>
<p>Vu le nombre d’individus, peu d’intérêt car pas lisible.</p>
</div>
<div id="représentation-graphique-des-individus-selon-les-modalités-de-la-variable-grav" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-individus-selon-les-modalit%C3%A9s-de-la-variable-grav" class="anchor"></a>Représentation graphique des individus selon les modalités de la variable “grav”</h2>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res2.mca</span>, invisible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"var"</span>,<span class="st">"quali.sup"</span><span class="op">)</span>,
     habillage <span class="op">=</span> <span class="st">"grav"</span>,
     title <span class="op">=</span> <span class="st">"Représentation des individus selon les modalités de la variable gravité"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-11-1.png" width="700"></p>
<p>Sur l’axe 2, les personnes idemnes (en bas) se détachent des personnes tuées (en haut)</p>
</div>
<div id="représentation-graphique-des-individus-selon-les-modalités-de-la-variable-catégorie-dusager" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-individus-selon-les-modalit%C3%A9s-de-la-variable-cat%C3%A9gorie-dusager" class="anchor"></a>Représentation graphique des individus selon les modalités de la variable “catégorie d’usager”</h2>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res2.mca</span>, invisible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"var"</span>,<span class="st">"quali.sup"</span><span class="op">)</span>,
     habillage <span class="op">=</span> <span class="st">"catu"</span>,
     title <span class="op">=</span> <span class="st">"Représentation des individus selon la catégorie d'usager"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-12-1.png" width="700"></p>
<p>Selon l’axe 2, on peut observer qu’un groupe “passager” se détache vers le bas (personnes indemnes), par oppoistion au groupe “piétons” vers le haut (personnes tuées)</p>
</div>
<div id="représentation-graphique-des-modalités-des-variables-1" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-modalit%C3%A9s-des-variables-1" class="anchor"></a>Représentation graphique des modalités des variables</h2>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res2.mca</span>, invisible <span class="op">=</span> <span class="st">"ind"</span>,
     title <span class="op">=</span> <span class="st">"Représentation des modalités actives (rouge) et des modalités illustratives (vert) selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-13-1.png" width="700"></p>
</div>
<div id="représentation-graphique-des-modalités-des-variables-sans-les-variables-illustratives" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-modalit%C3%A9s-des-variables-sans-les-variables-illustratives" class="anchor"></a>Représentation graphique des modalités des variables (sans les variables illustratives)</h2>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res2.mca</span>, invisible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ind"</span>,<span class="st">"quali.sup"</span><span class="op">)</span>,
     title <span class="op">=</span> <span class="st">"Représentation des modalités actives selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-14-1.png" width="700"></p>
<p>Sur l’axe 1: a) à gauche, plutôt des hommes, les classes d’âges intermédiaires (25-64 ans), conducteur et indemne b) à droite les âges extrêmes (moins de 15 ans ou 75 ans et plus), femmes, passagers ou piétons et blessés</p>
<p>Sur l’axe 2 : a) en haut : les personnes de plus de 75 ans / piéton / tué b) en bas : les personnes de moins de 25 ans / passager / blessé léger</p>
</div>
<div id="représentation-graphique-des-ellipses-de-confiance" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-ellipses-de-confiance" class="anchor"></a>Représentation graphique des ellipses de confiance</h2>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/FactoMineR/man/plotellipses.html">plotellipses</a></span><span class="op">(</span><span class="va">res2.mca</span>, keepvar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"grav"</span>, <span class="st">"sexe"</span>, <span class="st">"catu"</span>, <span class="st">"classe_age"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-15-1.png" width="700"> L’axe 1 distingue les hommes (à gauche) des femmes (à droite). De même, les conducteurs sont à gauche et les piétons à droite. L’axe 2 distingue les jeunes (en bas) des personnes âgées (en haut). Les jeunes sont plutôt des passagers, les classes d’âges intermédiaires des conducteurs et les personnes plus âgées des piétons.</p>
<p>Cette représentation graphique conforte les groupes mis en avant à l’étape précédente.</p>
</div>
<div id="résumé-des-stats-de-lacm-1" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9sum%C3%A9-des-stats-de-lacm-1" class="anchor"></a>Résumé des stats de l’ACM</h2>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">res2.mca</span>, nbelements<span class="op">=</span><span class="fl">5</span>, <span class="co"># nombre d'individus</span>
        ncp<span class="op">=</span><span class="fl">2</span>, <span class="co"># nombre de dimensions</span>
        nb.dec<span class="op">=</span><span class="fl">2</span><span class="op">)</span> </code></pre></div>
<pre><code>## 
## Call:
## MCA(X = base, quali.sup = c(4:20, 22), level.ventil = 0) 
## 
## 
## Eigenvalues
##                       Dim.1  Dim.2  Dim.3  Dim.4  Dim.5  Dim.6  Dim.7  Dim.8
## Variance               0.41   0.31   0.26   0.26   0.26   0.25   0.25   0.25
## % of var.             12.49   9.46   8.11   7.87   7.86   7.70   7.69   7.69
## Cumulative % of var.  12.49  21.95  30.06  37.93  45.79  53.50  61.19  68.88
##                       Dim.9 Dim.10 Dim.11 Dim.12 Dim.13
## Variance               0.25   0.24   0.21   0.18   0.13
## % of var.              7.56   7.43   6.50   5.55   4.09
## Cumulative % of var.  76.43  83.86  90.36  95.91 100.00
## 
## Individuals (the 5 first)
##                          Dim.1   ctr  cos2   Dim.2   ctr  cos2  
## 1                      |  0.17  0.00  0.01 |  1.43  0.00  0.36 |
## 2                      | -0.64  0.00  0.15 |  0.13  0.00  0.01 |
## 3                      | -0.49  0.00  0.05 |  0.35  0.00  0.03 |
## 4                      |  0.65  0.00  0.08 |  0.82  0.00  0.13 |
## 5                      | -0.29  0.00  0.04 |  0.26  0.00  0.03 |
## 
## Categories (the 5 first)
##                            Dim.1     ctr    cos2  v.test     Dim.2     ctr
## catu_Conducteur        |   -0.49   10.79    0.66 -563.39 |    0.08    0.39
## catu_Passager          |    1.16   14.48    0.29  370.16 |   -1.16   19.10
## catu_Piéton            |    1.74   16.69    0.30  377.99 |    1.62   18.97
## Blessé hospitalisé     |    0.40    2.05    0.04  141.79 |    0.69    7.91
## Blessé léger           |    0.46    4.62    0.12  236.97 |   -0.26    2.00
##                           cos2  v.test  
## catu_Conducteur           0.02   92.62 |
## catu_Passager             0.28 -369.82 |
## catu_Piéton               0.26  350.58 |
## Blessé hospitalisé        0.12  242.26 |
## Blessé léger              0.04 -135.59 |
## 
## Categorical variables (eta2)
##                          Dim.1 Dim.2  
## catu                   |  0.68  0.47 |
## grav                   |  0.26  0.27 |
## sexe                   |  0.21  0.00 |
## classe_age             |  0.47  0.48 |
## 
## Supplementary categories (the 5 first)
##                            Dim.1    cos2  v.test     Dim.2    cos2  v.test  
## secu1_Aucun équipement |    0.14    0.00   17.22 |    0.00    0.00   -0.46 |
## secu1_Autre            |   -0.20    0.00  -46.26 |   -0.19    0.00  -44.69 |
## secu1_Deux roues       |   -0.18    0.01  -58.78 |    0.01    0.00    2.14 |
## secu1_Piéton           |    1.74    0.30  377.99 |    1.62    0.26  350.58 |
## secu1_Voiture          |   -0.18    0.05 -151.37 |   -0.21    0.07 -178.17 |
## 
## Supplementary categorical variables (eta2)
##                          Dim.1 Dim.2  
## secu1                  |  0.30  0.26 |
## catv                   |  0.02  0.01 |
## lum                    |  0.00  0.01 |
## agg                    |  0.00  0.00 |
## atm                    |  0.00  0.00 |</code></pre>
</div>
</div>
<div id="etude-3---on-regarde-la-gravité-des-blessures-selon-les-caractéristiques-du-lieu-et-du-véhicule" class="section level1">
<h1 class="hasAnchor">
<a href="#etude-3---on-regarde-la-gravit%C3%A9-des-blessures-selon-les-caract%C3%A9ristiques-du-lieu-et-du-v%C3%A9hicule" class="anchor"></a>Etude 3 - on regarde la gravité des blessures selon les caractéristiques du lieu et du véhicule</h1>
<p>Dans cette 3e ACM, on s’intéresse aux conditions de la route, météo et du véhicules</p>
<div id="acm-2" class="section level2">
<h2 class="hasAnchor">
<a href="#acm-2" class="anchor"></a>ACM</h2>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res3.mca</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/FactoMineR/man/MCA.html">MCA</a></span><span class="op">(</span><span class="va">base</span>, quali.sup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span>,<span class="fl">21</span><span class="op">)</span>, 
                level.ventil <span class="op">=</span> <span class="fl">0.025</span><span class="op">)</span> </code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-17-1.png" width="700"><img src="ACM_classif_files/figure-html/unnamed-chunk-17-2.png" width="700"><img src="ACM_classif_files/figure-html/unnamed-chunk-17-3.png" width="700"></p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># toutes les modalités représentant moins de 2.5 % sont ventilées aléatoirement dans les autres modalités (les tués représentent 2,7 % des accidents, d'où le filtre à 2,5 % car on veut garder la modalité "tué")</span></code></pre></div>
</div>
<div id="réprésentation-graphique-des-poids-des-dimensions-2" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9pr%C3%A9sentation-graphique-des-poids-des-dimensions-2" class="anchor"></a>Réprésentation graphique des poids des dimensions</h2>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Tableau avec les poids</span>
<span class="va">res3.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span></code></pre></div>
<pre><code>##     dim 1     dim 2     dim 3     dim 4     dim 5     dim 6     dim 7     dim 8 
## 4.7567577 3.6920761 3.4158827 3.3645584 3.0693229 2.6650523 2.6212283 2.1486322 
##     dim 9    dim 10    dim 11    dim 12    dim 13    dim 14    dim 15    dim 16 
## 2.0230725 1.9940286 1.8806384 1.8529327 1.7613262 1.7230204 1.7138172 1.7023843 
##    dim 17    dim 18    dim 19    dim 20    dim 21    dim 22    dim 23    dim 24 
## 1.6839468 1.6750757 1.6711558 1.6648942 1.6588662 1.6525973 1.6477076 1.6438101 
##    dim 25    dim 26    dim 27    dim 28    dim 29    dim 30    dim 31    dim 32 
## 1.6419302 1.6404337 1.6375529 1.6318397 1.6293520 1.6240980 1.6166087 1.6089957 
##    dim 33    dim 34    dim 35    dim 36    dim 37    dim 38    dim 39    dim 40 
## 1.5986741 1.5938603 1.5809162 1.5723675 1.5566026 1.5370737 1.5047874 1.4790234 
##    dim 41    dim 42    dim 43    dim 44    dim 45    dim 46    dim 47    dim 48 
## 1.4490244 1.4028945 1.3717131 1.3468538 1.3105019 1.2852421 1.2379244 1.2116649 
##    dim 49    dim 50    dim 51    dim 52    dim 53    dim 54    dim 55    dim 56 
## 1.1624723 1.1481275 1.1056598 1.0177428 0.9989133 0.9372519 0.8349646 0.7702196 
##    dim 57    dim 58    dim 59    dim 60    dim 61 
## 0.6813850 0.5246715 0.4783359 0.3763595 0.2111768</code></pre>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Histogramme</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="va">res3.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>, names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Dim"</span>, <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">res3.mca</span><span class="op">$</span><span class="va">eig</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-18-1.png" width="700"></p>
<p>On garde 5 axes, soit 18.3 %.</p>
</div>
<div id="réprésentation-graphique-des-individus-2" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9pr%C3%A9sentation-graphique-des-individus-2" class="anchor"></a>Réprésentation graphique des individus</h2>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res3.mca</span>, invisible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"var"</span>,<span class="st">"quali.sup"</span><span class="op">)</span>,
     title <span class="op">=</span> <span class="st">"Représentation des individus selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-19-1.png" width="700"></p>
<p>Vu le nb d’individus, pas d’intérêt car pas lisible</p>
</div>
<div id="représentation-graphique-des-individus-selon-les-modalités-de-la-variable-grav-1" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-individus-selon-les-modalit%C3%A9s-de-la-variable-grav-1" class="anchor"></a>Représentation graphique des individus selon les modalités de la variable “grav”</h2>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res3.mca</span>, invisible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"var"</span>,<span class="st">"quali.sup"</span><span class="op">)</span>,
     habillage <span class="op">=</span> <span class="st">"grav"</span>,
     title <span class="op">=</span> <span class="st">"Représentation des individus selon les modalités de la variable gravité"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-20-1.png" width="700"></p>
<p>Sur l’axe 2, les personnes indemnes (en bas) se détachent des personnes tuées (en haut)</p>
</div>
<div id="représentation-graphique-des-modalités-des-variables-2" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-modalit%C3%A9s-des-variables-2" class="anchor"></a>Représentation graphique des modalités des variables</h2>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res3.mca</span>, invisible <span class="op">=</span> <span class="st">"ind"</span>,
     title <span class="op">=</span> <span class="st">"Réprésentation des modalités actives (rouge) et des modalités illustratives (vert) selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-21-1.png" width="700"></p>
</div>
<div id="représentation-graphique-des-modalités-des-variables-sans-les-variables-illustratives-1" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-modalit%C3%A9s-des-variables-sans-les-variables-illustratives-1" class="anchor"></a>Représentation graphique des modalités des variables (sans les variables illustratives)</h2>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res3.mca</span>, invisible <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ind"</span>,<span class="st">"quali.sup"</span><span class="op">)</span>,
     title <span class="op">=</span> <span class="st">"Représentation des modalités actives selon les 2 premiers axes de l'ACM"</span><span class="op">)</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-22-1.png" width="700"></p>
<p>L’axe 1 est discriminant sur la catégorie de route : voie communale à gauche contre route nationale/autoroute à droite. De même, on a les accidents en agglomération à droite et ceux hors agglo à gauche (cohérent avec l’analyse précédente). Enfin, la luminosité conforte cette analyse : nuit avec éclairage (en agglo - à gauche) et nuit sans écalirage (hors agglo - à droite)</p>
<p>L’axe 2 distingue le profil : accidents en pente en haut et accident sur route “plate” en bas. De même, le régime de circulation explique cet axe : sens unique ou chaussées séparées en bas contre bidirectionnelle en haut. Enfin, on a une nette opposition entre les personnes indemnes en bas et les blessés/hospitalisés en haut.</p>
</div>
<div id="représentation-graphique-des-ellipses-de-confiance-1" class="section level2">
<h2 class="hasAnchor">
<a href="#repr%C3%A9sentation-graphique-des-ellipses-de-confiance-1" class="anchor"></a>Représentation graphique des ellipses de confiance</h2>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#plotellipses(res3.mca, keepvar = c("grav", "catr", "agg", "secu1", "catv", "col", "plan"))</span></code></pre></div>
</div>
<div id="résumé-des-stats-de-lacm-2" class="section level2">
<h2 class="hasAnchor">
<a href="#r%C3%A9sum%C3%A9-des-stats-de-lacm-2" class="anchor"></a>Résumé des stats de l’ACM</h2>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">res3.mca</span>, nbelements<span class="op">=</span><span class="fl">20</span>, <span class="co"># nombre d'individus (permet aussi de voir la contribution de toutes les variables aux axes)</span>
        ncp<span class="op">=</span><span class="fl">5</span>, <span class="co"># nombre de dimensions</span>
        nb.dec<span class="op">=</span><span class="fl">2</span><span class="op">)</span> </code></pre></div>
<pre><code>## 
## Call:
## MCA(X = base, quali.sup = c(1, 3, 21), level.ventil = 0.025) 
## 
## 
## Eigenvalues
##                       Dim.1  Dim.2  Dim.3  Dim.4  Dim.5  Dim.6  Dim.7  Dim.8
## Variance               0.15   0.12   0.11   0.11   0.10   0.09   0.08   0.07
## % of var.              4.76   3.69   3.42   3.36   3.07   2.67   2.62   2.15
## Cumulative % of var.   4.76   8.45  11.86  15.23  18.30  20.96  23.58  25.73
##                       Dim.9 Dim.10 Dim.11 Dim.12 Dim.13 Dim.14 Dim.15 Dim.16
## Variance               0.06   0.06   0.06   0.06   0.06   0.06   0.06   0.05
## % of var.              2.02   1.99   1.88   1.85   1.76   1.72   1.71   1.70
## Cumulative % of var.  27.76  29.75  31.63  33.48  35.25  36.97  38.68  40.38
##                      Dim.17 Dim.18 Dim.19 Dim.20 Dim.21 Dim.22 Dim.23 Dim.24
## Variance               0.05   0.05   0.05   0.05   0.05   0.05   0.05   0.05
## % of var.              1.68   1.68   1.67   1.66   1.66   1.65   1.65   1.64
## Cumulative % of var.  42.07  43.74  45.41  47.08  48.74  50.39  52.04  53.68
##                      Dim.25 Dim.26 Dim.27 Dim.28 Dim.29 Dim.30 Dim.31 Dim.32
## Variance               0.05   0.05   0.05   0.05   0.05   0.05   0.05   0.05
## % of var.              1.64   1.64   1.64   1.63   1.63   1.62   1.62   1.61
## Cumulative % of var.  55.32  56.97  58.60  60.23  61.86  63.49  65.10  66.71
##                      Dim.33 Dim.34 Dim.35 Dim.36 Dim.37 Dim.38 Dim.39 Dim.40
## Variance               0.05   0.05   0.05   0.05   0.05   0.05   0.05   0.05
## % of var.              1.60   1.59   1.58   1.57   1.56   1.54   1.50   1.48
## Cumulative % of var.  68.31  69.91  71.49  73.06  74.62  76.15  77.66  79.14
##                      Dim.41 Dim.42 Dim.43 Dim.44 Dim.45 Dim.46 Dim.47 Dim.48
## Variance               0.05   0.05   0.04   0.04   0.04   0.04   0.04   0.04
## % of var.              1.45   1.40   1.37   1.35   1.31   1.29   1.24   1.21
## Cumulative % of var.  80.59  81.99  83.36  84.71  86.02  87.30  88.54  89.75
##                      Dim.49 Dim.50 Dim.51 Dim.52 Dim.53 Dim.54 Dim.55 Dim.56
## Variance               0.04   0.04   0.04   0.03   0.03   0.03   0.03   0.02
## % of var.              1.16   1.15   1.11   1.02   1.00   0.94   0.83   0.77
## Cumulative % of var.  90.92  92.06  93.17  94.19  95.19  96.12  96.96  97.73
##                      Dim.57 Dim.58 Dim.59 Dim.60 Dim.61
## Variance               0.02   0.02   0.02   0.01   0.01
## % of var.              0.68   0.52   0.48   0.38   0.21
## Cumulative % of var.  98.41  98.93  99.41  99.79 100.00
## 
## Individuals (the 20 first)
##                              Dim.1   ctr  cos2   Dim.2   ctr  cos2   Dim.3
## 1                          |  0.14  0.00  0.01 |  0.37  0.00  0.05 | -0.07
## 2                          |  0.16  0.00  0.01 |  0.14  0.00  0.01 | -0.04
## 3                          | -0.04  0.00  0.00 |  0.00  0.00  0.00 | -0.05
## 4                          | -0.25  0.00  0.02 |  0.10  0.00  0.00 | -0.02
## 5                          | -0.44  0.00  0.06 |  0.61  0.00  0.11 | -0.42
## 6                          | -0.10  0.00  0.00 |  0.02  0.00  0.00 | -0.11
## 7                          | -0.44  0.00  0.06 |  0.40  0.00  0.05 | -0.43
## 8                          | -0.03  0.00  0.00 | -0.14  0.00  0.01 |  0.08
## 9                          | -0.66  0.00  0.19 | -0.05  0.00  0.00 | -0.51
## 10                         | -0.29  0.00  0.05 | -0.48  0.00  0.13 | -0.20
## 11                         |  0.27  0.00  0.02 |  0.27  0.00  0.02 |  0.85
## 12                         |  0.22  0.00  0.01 |  0.35  0.00  0.03 |  0.82
## 13                         |  0.10  0.00  0.00 |  0.52  0.00  0.05 |  0.87
## 14                         | -0.10  0.00  0.00 |  0.07  0.00  0.00 |  0.04
## 15                         | -0.24  0.00  0.03 | -0.37  0.00  0.07 |  0.24
## 16                         | -0.12  0.00  0.01 |  0.43  0.00  0.07 | -0.37
## 17                         | -0.46  0.00  0.08 |  0.47  0.00  0.08 | -0.44
## 18                         | -0.13  0.00  0.01 | -0.11  0.00  0.01 | -0.13
## 19                         | -0.21  0.00  0.01 | -0.14  0.00  0.01 | -0.14
## 20                         | -0.55  0.00  0.08 |  0.44  0.00  0.05 | -0.44
##                              ctr  cos2   Dim.4   ctr  cos2   Dim.5   ctr  cos2
## 1                           0.00  0.00 |  0.17  0.00  0.01 | -0.41  0.00  0.06
## 2                           0.00  0.00 |  0.25  0.00  0.03 | -0.45  0.00  0.08
## 3                           0.00  0.00 | -0.01  0.00  0.00 | -0.20  0.00  0.01
## 4                           0.00  0.00 | -0.24  0.00  0.02 | -0.16  0.00  0.01
## 5                           0.00  0.05 | -0.25  0.00  0.02 |  0.20  0.00  0.01
## 6                           0.00  0.00 |  0.10  0.00  0.00 | -0.22  0.00  0.02
## 7                           0.00  0.05 | -0.09  0.00  0.00 | -0.02  0.00  0.00
## 8                           0.00  0.00 |  0.00  0.00  0.00 | -0.30  0.00  0.04
## 9                           0.00  0.12 | -0.26  0.00  0.03 |  0.38  0.00  0.07
## 10                          0.00  0.02 |  0.11  0.00  0.01 | -0.10  0.00  0.01
## 11                          0.00  0.15 | -0.28  0.00  0.02 | -0.15  0.00  0.00
## 12                          0.00  0.14 | -0.38  0.00  0.03 | -0.05  0.00  0.00
## 13                          0.00  0.14 | -0.48  0.00  0.04 | -0.17  0.00  0.01
## 14                          0.00  0.00 | -0.19  0.00  0.01 | -0.27  0.00  0.03
## 15                          0.00  0.03 | -0.20  0.00  0.02 | -0.24  0.00  0.03
## 16                          0.00  0.05 | -0.29  0.00  0.03 |  0.17  0.00  0.01
## 17                          0.00  0.07 | -0.08  0.00  0.00 | -0.03  0.00  0.00
## 18                          0.00  0.01 |  0.27  0.00  0.03 | -0.45  0.00  0.09
## 19                          0.00  0.01 |  0.24  0.00  0.02 | -0.30  0.00  0.03
## 20                          0.00  0.05 | -0.10  0.00  0.00 |  0.12  0.00  0.00
##                             
## 1                          |
## 2                          |
## 3                          |
## 4                          |
## 5                          |
## 6                          |
## 7                          |
## 8                          |
## 9                          |
## 10                         |
## 11                         |
## 12                         |
## 13                         |
## 14                         |
## 15                         |
## 16                         |
## 17                         |
## 18                         |
## 19                         |
## 20                         |
## 
## Categories (the 20 first)
##                                Dim.1     ctr    cos2  v.test     Dim.2     ctr
## Blessé hospitalisé         |    0.00    0.00    0.00    0.35 |    0.96    8.28
## Blessé léger               |   -0.25    0.75    0.03 -127.77 |   -0.03    0.01
## Indemne                    |    0.17    0.41    0.02   98.82 |   -0.54    5.36
## Tué                        |    0.67    0.42    0.01   77.12 |    1.34    2.18
## secu1_Aucun équipement     |   -0.21    0.05    0.00  -26.32 |    0.90    1.09
## secu1_Autre                |   -0.30    0.31    0.01  -68.74 |   -0.20    0.18
## secu1_Deux roues           |   -0.81    4.14    0.15 -265.70 |    0.98    7.71
## secu1_Piéton               |   -0.73    1.65    0.05 -158.99 |   -0.14    0.08
## secu1_Voiture              |    0.42    3.58    0.26  352.86 |   -0.29    2.20
## 2 roues motorisé           |   -0.80    4.42    0.16 -278.03 |    0.85    6.49
## Bicyclette                 |   -0.96    1.28    0.04 -136.40 |    0.52    0.47
## VL seul                    |    0.26    1.64    0.16  275.81 |   -0.23    1.69
## VU seul                    |    0.29    0.18    0.01   50.91 |   -0.50    0.66
## Crépuscule ou aube         |    0.17    0.06    0.00   30.22 |    0.13    0.05
## Nuit avec éclairage public |   -0.52    1.43    0.05 -153.59 |   -0.20    0.28
## Nuit sans éclairage        |    1.30    5.72    0.18  297.41 |    0.55    1.32
## Plein jour                 |   -0.09    0.17    0.02  -87.31 |   -0.05    0.06
## En agglomération           |   -0.58    7.09    0.54 -509.90 |   -0.19    1.04
## Hors agglomération         |    0.94   11.57    0.54  509.90 |    0.32    1.70
## atm_Normale                |   -0.06    0.10    0.02  -97.36 |    0.00    0.00
##                               cos2  v.test     Dim.3     ctr    cos2  v.test  
## Blessé hospitalisé            0.23  335.47 |   -0.10    0.09    0.00  -33.55 |
## Blessé léger                  0.00  -13.40 |   -0.08    0.12    0.00  -42.72 |
## Indemne                       0.20 -313.38 |    0.11    0.25    0.01   65.27 |
## Tué                           0.05  155.78 |    0.10    0.01    0.00   11.76 |
## secu1_Aucun équipement        0.03  110.43 |    0.14    0.03    0.00   16.82 |
## secu1_Autre                   0.00  -46.45 |    0.31    0.46    0.01   71.59 |
## secu1_Deux roues              0.21  319.37 |   -0.77    5.13    0.13 -250.42 |
## secu1_Piéton                  0.00  -31.10 |    0.46    0.90    0.02   99.39 |
## secu1_Voiture                 0.12 -243.80 |    0.11    0.32    0.02   89.86 |
## 2 roues motorisé              0.18  296.65 |   -0.65    4.10    0.11 -226.68 |
## Bicyclette                    0.01   73.11 |   -0.36    0.24    0.01  -50.46 |
## VL seul                       0.13 -246.63 |    0.21    1.49    0.10  222.87 |
## VU seul                       0.02  -87.02 |   -0.03    0.00    0.00   -5.28 |
## Crépuscule ou aube            0.00   23.36 |    0.45    0.62    0.01   81.28 |
## Nuit avec éclairage public    0.01  -60.32 |    0.97    6.98    0.17  287.30 |
## Nuit sans éclairage           0.03  125.74 |    0.73    2.51    0.06  167.01 |
## Plein jour                    0.00  -46.02 |   -0.36    4.37    0.29 -372.60 |
## En agglomération              0.06 -172.11 |    0.10    0.28    0.02   85.35 |
## Hors agglomération            0.06  172.11 |   -0.16    0.45    0.02  -85.35 |
## atm_Normale                   0.00   -3.15 |   -0.19    1.53    0.23 -329.29 |
##                              Dim.4     ctr    cos2  v.test     Dim.5     ctr
## Blessé hospitalisé           -0.17    0.27    0.01  -58.08 |   -0.02    0.00
## Blessé léger                 -0.30    1.61    0.05 -157.07 |    0.34    2.21
## Indemne                       0.37    2.66    0.09  210.90 |   -0.26    1.51
## Tué                          -0.26    0.09    0.00  -30.61 |   -0.37    0.20
## secu1_Aucun équipement       -0.24    0.08    0.00  -29.14 |   -0.15    0.04
## secu1_Autre                  -0.05    0.01    0.00  -10.81 |   -0.14    0.10
## secu1_Deux roues             -0.59    3.08    0.08 -192.70 |    0.96    8.99
## secu1_Piéton                 -0.45    0.89    0.02  -98.28 |   -0.57    1.56
## secu1_Voiture                 0.27    2.07    0.11  225.72 |   -0.18    1.00
## 2 roues motorisé             -0.60    3.60    0.09 -210.96 |    0.90    8.79
## Bicyclette                   -0.09    0.02    0.00  -12.56 |   -0.01    0.00
## VL seul                       0.16    0.84    0.06  165.53 |   -0.24    2.22
## VU seul                       0.28    0.22    0.00   48.23 |   -0.20    0.12
## Crépuscule ou aube           -0.28    0.25    0.01  -50.87 |    0.03    0.00
## Nuit avec éclairage public   -0.85    5.37    0.13 -250.07 |    0.20    0.34
## Nuit sans éclairage          -0.55    1.44    0.03 -125.49 |    0.50    1.33
## Plein jour                    0.29    2.90    0.19  301.17 |   -0.12    0.53
## En agglomération             -0.09    0.27    0.01  -83.45 |   -0.16    0.80
## Hors agglomération            0.15    0.44    0.01   83.45 |    0.25    1.31
## atm_Normale                   0.13    0.69    0.10  219.71 |    0.02    0.01
##                               cos2  v.test  
## Blessé hospitalisé            0.00   -7.24 |
## Blessé léger                  0.06  176.04 |
## Indemne                       0.05 -151.52 |
## Tué                           0.00  -43.00 |
## secu1_Aucun équipement        0.00  -18.61 |
## secu1_Autre                   0.00  -31.31 |
## secu1_Deux roues              0.21  314.28 |
## secu1_Piéton                  0.03 -124.13 |
## secu1_Voiture                 0.05 -149.70 |
## 2 roues motorisé              0.21  314.78 |
## Bicyclette                    0.00   -1.75 |
## VL seul                       0.14 -257.51 |
## VU seul                       0.00  -34.30 |
## Crépuscule ou aube            0.00    4.77 |
## Nuit avec éclairage public    0.01   60.35 |
## Nuit sans éclairage           0.03  115.09 |
## Plein jour                    0.03 -123.14 |
## En agglomération              0.04 -138.01 |
## Hors agglomération            0.04  138.01 |
## atm_Normale                   0.00   26.69 |
## 
## Categorical variables (eta2)
##                              Dim.1 Dim.2 Dim.3 Dim.4 Dim.5  
## grav                       |  0.05  0.36  0.01  0.10  0.07 |
## secu1                      |  0.28  0.25  0.14  0.13  0.22 |
## catv                       |  0.22  0.21  0.12  0.10  0.21 |
## lum                        |  0.21  0.04  0.30  0.20  0.04 |
## agg                        |  0.54  0.06  0.02  0.01  0.04 |
## atm                        |  0.02  0.00  0.24  0.11  0.00 |
## col                        |  0.23  0.26  0.07  0.06  0.17 |
## intersection               |  0.21  0.02  0.01  0.01  0.00 |
## mois_acc                   |  0.01  0.01  0.16  0.06  0.00 |
## jour_acc                   |  0.02  0.03  0.01  0.01  0.00 |
## catr                       |  0.53  0.26  0.02  0.02  0.29 |
## circ                       |  0.22  0.20  0.07  0.11  0.34 |
## prof                       |  0.02  0.13  0.11  0.24  0.08 |
## plan                       |  0.09  0.20  0.13  0.27  0.09 |
## surf                       |  0.07  0.02  0.43  0.39  0.12 |
## infra                      |  0.00  0.00  0.00  0.00  0.00 |
## situ                       |  0.05  0.02  0.05  0.07  0.03 |
## gr_dep                     |  0.12  0.16  0.00  0.03  0.11 |
## cl_heure                   |  0.01  0.01  0.18  0.14  0.05 |
## 
## Supplementary categories
##                                Dim.1    cos2  v.test     Dim.2    cos2  v.test
## catu_Conducteur            |   -0.01    0.00   -7.93 |   -0.01    0.00  -15.02
## catu_Passager              |    0.40    0.03  128.21 |    0.13    0.00   40.70
## catu_Piéton                |   -0.73    0.05 -158.99 |   -0.14    0.00  -31.10
## Féminin                    |    0.07    0.00   33.99 |   -0.10    0.00  -48.45
## Masculin                   |   -0.03    0.00  -33.99 |    0.05    0.00   48.45
## 0-14 ans                   |    0.00    0.00    0.41 |   -0.02    0.00   -2.63
## 15-24 ans                  |   -0.06    0.00  -21.29 |    0.25    0.02   90.45
## 25-34 ans                  |    0.01    0.00    3.78 |   -0.09    0.00  -31.38
## 35-44 ans                  |    0.03    0.00    7.81 |   -0.14    0.00  -43.14
## 45-54 ans                  |    0.02    0.00    5.59 |   -0.07    0.00  -19.85
## 55-64 ans                  |    0.02    0.00    4.70 |   -0.03    0.00   -6.71
## 65-74 ans                  |    0.05    0.00    7.84 |   -0.01    0.00   -1.02
## 75 ans et +                |   -0.03    0.00   -5.07 |    0.05    0.00    8.70
##                                Dim.3    cos2  v.test     Dim.4    cos2  v.test
## catu_Conducteur            |   -0.08    0.02  -87.11 |    0.05    0.01   57.18
## catu_Passager              |    0.08    0.00   26.58 |    0.02    0.00    7.29
## catu_Piéton                |    0.46    0.02   99.39 |   -0.45    0.02  -98.28
## Féminin                    |    0.07    0.00   34.91 |    0.07    0.00   31.24
## Masculin                   |   -0.03    0.00  -34.91 |   -0.03    0.00  -31.24
## 0-14 ans                   |    0.03    0.00    5.09 |    0.01    0.00    2.13
## 15-24 ans                  |    0.08    0.00   27.39 |   -0.19    0.01  -65.95
## 25-34 ans                  |    0.03    0.00    9.58 |   -0.08    0.00  -27.51
## 35-44 ans                  |   -0.03    0.00   -9.97 |    0.02    0.00    7.51
## 45-54 ans                  |   -0.08    0.00  -23.69 |    0.07    0.00   18.66
## 55-64 ans                  |   -0.08    0.00  -17.80 |    0.13    0.00   29.71
## 65-74 ans                  |   -0.02    0.00   -3.87 |    0.24    0.00   42.07
## 75 ans et +                |    0.06    0.00    9.41 |    0.26    0.00   41.62
##                                Dim.5    cos2  v.test  
## catu_Conducteur            |    0.07    0.01   75.28 |
## catu_Passager              |    0.02    0.00    5.66 |
## catu_Piéton                |   -0.57    0.03 -124.13 |
## Féminin                    |   -0.17    0.01  -78.91 |
## Masculin                   |    0.08    0.01   78.91 |
## 0-14 ans                   |   -0.25    0.00  -42.16 |
## 15-24 ans                  |    0.09    0.00   32.29 |
## 25-34 ans                  |    0.16    0.01   56.96 |
## 35-44 ans                  |    0.08    0.00   25.24 |
## 45-54 ans                  |    0.03    0.00    9.11 |
## 55-64 ans                  |   -0.08    0.00  -18.21 |
## 65-74 ans                  |   -0.33    0.01  -57.89 |
## 75 ans et +                |   -0.55    0.02  -89.56 |
## 
## Supplementary categorical variables (eta2)
##                              Dim.1 Dim.2 Dim.3 Dim.4 Dim.5  
## catu                       |  0.08  0.00  0.02  0.02  0.03 |
## sexe                       |  0.00  0.00  0.00  0.00  0.01 |
## classe_age                 |  0.00  0.02  0.00  0.02  0.03 |</code></pre>
</div>
</div>
<div id="classification-avec-mclust" class="section level1">
<h1 class="hasAnchor">
<a href="#classification-avec-mclust" class="anchor"></a>Classification avec Mclust</h1>
<p>Etape 1 : on fait un Mclust avec 1 à 10 classes</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod_classif</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mclust-org.github.io/mclust/reference/Mclust.html">Mclust</a></span><span class="op">(</span><span class="va">base</span>, G <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">)</span>
<span class="va">mod_classif</span><span class="op">$</span><span class="va">BIC</span></code></pre></div>
<p>On constate que les meilleurs résultats sont pour les modèles EEV.</p>
<p>Etape 2 : on relance le mclust sur les modèles EEV uniquement et on teste de 1 à 10 classes</p>
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod_classif</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mclust-org.github.io/mclust/reference/Mclust.html">Mclust</a></span><span class="op">(</span><span class="va">base</span>, G <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">10</span>, modelNames <span class="op">=</span> <span class="st">"EEV"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span>, <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">mod_classif</span><span class="op">$</span><span class="va">BIC</span><span class="op">)</span>, type<span class="op">=</span><span class="st">'h'</span><span class="op">)</span> <span class="co"># pour afficher des BIC positifs</span></code></pre></div>
<p><img src="ACM_classif_files/figure-html/unnamed-chunk-26-1.png" width="700"> On retient 6 classes plutôt que 4 parce que ça minimise le BIC, et 6 plutôt que 10 car cela permet modèle plus parcimonieux et un nombre de classes plus facilement analysable.</p>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod_classif</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mclust-org.github.io/mclust/reference/Mclust.html">Mclust</a></span><span class="op">(</span><span class="va">base</span>, G <span class="op">=</span> <span class="fl">6</span>, modelNames <span class="op">=</span> <span class="st">"EEV"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod_classif</span><span class="op">)</span> </code></pre></div>
<pre><code>## ---------------------------------------------------- 
## Gaussian finite mixture model fitted by EM algorithm 
## ---------------------------------------------------- 
## 
## Mclust EEV (ellipsoidal, equal volume and shape) model with 6 components: 
## 
##  log-likelihood      n   df       BIC       ICL
##       -12001227 480116 1545 -24022665 -24036721
## 
## Clustering table:
##      1      2      3      4      5      6 
## 204871  81269  52820  55645  41641  43870</code></pre>
<div id="analyse-des-classes" class="section level2">
<h2 class="hasAnchor">
<a href="#analyse-des-classes" class="anchor"></a>Analyse des classes</h2>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># ajout des classes dans la base</span>
<span class="va">base_comp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind.data.frame</a></span><span class="op">(</span><span class="va">base</span>,classe_mclust<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">mod_classif</span><span class="op">$</span><span class="va">classification</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">base_comp</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "catu"          "grav"          "sexe"          "secu1"        
##  [5] "catv"          "lum"           "agg"           "atm"          
##  [9] "col"           "intersection"  "mois_acc"      "jour_acc"     
## [13] "catr"          "circ"          "prof"          "plan"         
## [17] "surf"          "infra"         "situ"          "gr_dep"       
## [21] "classe_age"    "cl_heure"      "classe_mclust"</code></pre>
</div>
<div id="quelles-modalités-sont-le-plus-liées-aux-modalité-de-la-gravité-des-blessures" class="section level2">
<h2 class="hasAnchor">
<a href="#quelles-modalit%C3%A9s-sont-le-plus-li%C3%A9es-aux-modalit%C3%A9-de-la-gravit%C3%A9-des-blessures" class="anchor"></a>Quelles modalités sont le plus liées aux modalité de la gravité des blessures ?</h2>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res_mclust</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/FactoMineR/man/catdes.html">catdes</a></span><span class="op">(</span><span class="va">base_comp</span>, num.var <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>  <span class="co"># on caractérise la variable "grav" (2e colonne dans la base)</span>
<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">res_mclust</span><span class="op">$</span><span class="va">category</span>, <span class="kw">function</span><span class="op">(</span><span class="va">.x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">.x</span><span class="op">)</span>, n<span class="op">=</span><span class="fl">8</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## $`Blessé hospitalisé`
##                                 Cla/Mod   Mod/Cla    Global p.value v.test
## classe_mclust=4                34.17198 19.399300 11.589907       0    Inf
## classe_age=75 ans et +         30.99654  7.961722  5.243941       0    Inf
## gr_dep=moins 500 000 hab       29.72862 21.345862 14.658957       0    Inf
## gr_dep=500 000 - 1 000 000 hab 25.26178 27.442639 22.178182       0    Inf
## plan=Non Rectiligne            29.23810 22.774156 15.902199       0    Inf
## circ=Bidirectionnelle          24.17390 71.522868 60.403527       0    Inf
## catr=Route Départementale      29.42932 50.206593 34.829291       0    Inf
## intersection=Hors intersection 22.17594 74.566156 68.647369       0    Inf
## 
## $`Blessé léger`
##                         Cla/Mod   Mod/Cla    Global p.value v.test
## classe_mclust=4        53.12247 17.162598 11.589907       0    Inf
## classe_age=0-14 ans    50.03429  8.048887  5.770897       0    Inf
## gr_dep=plus de 2 M hab 42.46099 24.759195 20.918070       0    Inf
## circ=A sens unique     42.28941 20.814585 17.656775       0    Inf
## catr=Voie Communale    40.55460 50.955381 45.073899       0    Inf
## agg=En agglomération   38.78188 67.045026 62.017304       0    Inf
## catv=Bicyclette        57.15542  6.035939  3.788459       0    Inf
## catv=2 roues motorisé  52.60697 28.089529 19.154746       0    Inf
## 
## $Indemne
##                                Cla/Mod   Mod/Cla    Global p.value v.test
## classe_mclust=1               51.31082 53.412971 42.671146       0    Inf
## situ=Sur chaussée             42.47904 80.163408 77.356722       0    Inf
## plan=Rectiligne               42.58874 78.549652 75.604229       0    Inf
## col=3 véhicules et plus       54.89421 17.216780 12.856476       0    Inf
## col=2 véhicules - par le côté 45.45559 32.059672 28.911346       0    Inf
## agg=En agglomération          43.25267 65.437889 62.017304       0    Inf
## catv=VU seul                  59.34120  8.000183  5.526373       0    Inf
## catv=VL seul                  49.15534 79.232043 66.073407       0    Inf
## 
## $Tué
##                                 Cla/Mod  Mod/Cla    Global p.value v.test
## classe_age=75 ans et +         8.694443 16.76881  5.243941       0    Inf
## gr_dep=moins 500 000 hab       5.112248 27.56243 14.658957       0    Inf
## plan=Non Rectiligne            5.041323 29.48522 15.902199       0    Inf
## circ=Bidirectionnelle          3.486123 77.44753 60.403527       0    Inf
## catr=Route Départementale      4.915053 62.96154 34.829291       0    Inf
## intersection=Hors intersection 3.305652 83.46101 68.647369       0    Inf
## agg=Hors agglomération         5.049325 70.53777 37.982696       0    Inf
## lum=Nuit sans éclairage        6.963995 25.20300  9.839914       0    Inf</code></pre>
<div id="classe-blessés-hospitalisés" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-bless%C3%A9s-hospitalis%C3%A9s" class="anchor"></a>Classe “Blessés hospitalisés”</h3>
<p>Il y a une sur-représentation des personnes âgées de 75 ans et + : 31.0 % d’entre eux ont été blessés hospitalisés dans l’accident. Parmi les personnes blessées hospitalisées dans l’accident, 8.0 % sont des personnes de 75 ans et plus. Enfin, les personnes âgées de 75 ans et plus représentent 5.2 % des personnes accidentées. De même, il y a une sur-représentation des départements moins peuplés (29.7 % pour les moins de 500 000 hab contre 14.7% dans la base totale) Le lieu était plutôt une route départementale, non rectiligne avec une circulation bidirectionnelle.</p>
</div>
<div id="classe-blessés-léger" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-bless%C3%A9s-l%C3%A9ger" class="anchor"></a>Classe “Blessés léger”</h3>
<p>Il y a une sur-représentation des personnes de moins de 15 ans : 50.0 % d’entre eux ont été blessés légers dans l’accident. Parmi les personnes blessées légers dans l’accident, 8.0 % sont des personnes de moins de 15 ans. Enfin, les personnes âgées de moins de 15 ans représentent 5.8 % des personnes accidentées. De même, il y a une sur-représentation des départements de plus de 2 millions d’habitants. Le lieu de l’accident était plus souvent une voie communale, en agglomération, sur une route à sens unique et le véhicule était un vélo.</p>
</div>
<div id="classe-indemne" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-indemne" class="anchor"></a>Classe “Indemne”</h3>
<p>Aucune catégorie d’usagers ne ressort. Ce sont plutôt des accidents avec plusieurs véhicules (2 ou plus), avec des véhicules utilitaires et en agglomération.</p>
</div>
<div id="classe-tué" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-tu%C3%A9" class="anchor"></a>Classe “Tué”</h3>
<p>Comme pour les blessés hospitalisés, il y a une sur-reprsentation des personnes âgées de 75 ans et plus, dans des départements de moins de 500 000 habitants. Le lieu est caractérisé par une route départementale bidirectionnelle, non rectiligne, hors agglomération. Les accidents ont eu lieu la nuit sans éclairage.</p>
</div>
</div>
<div id="quelles-modalités-sont-les-plus-présentes-dans-chaque-classe" class="section level2">
<h2 class="hasAnchor">
<a href="#quelles-modalit%C3%A9s-sont-les-plus-pr%C3%A9sentes-dans-chaque-classe" class="anchor"></a>Quelles modalités sont les plus présentes dans chaque classe ?</h2>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res_mclust2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/FactoMineR/man/catdes.html">catdes</a></span><span class="op">(</span><span class="va">base_comp</span>, num.var <span class="op">=</span> <span class="fl">23</span><span class="op">)</span>  <span class="co"># on choisit la variable "classe"</span>
<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">res_mclust2</span><span class="op">$</span><span class="va">category</span>, <span class="kw">function</span><span class="op">(</span><span class="va">.x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">.x</span><span class="op">)</span>, n<span class="op">=</span><span class="fl">10</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## $`1`
##                                 Cla/Mod    Mod/Cla    Global p.value v.test
## classe_age=75 ans et +         56.05513   6.888725  5.243941       0    Inf
## infra=Non                      48.01793  97.852307 86.956486       0    Inf
## surf=Normale                   52.31037  95.414187 77.832232       0    Inf
## intersection=Hors intersection 45.43383  73.091848 68.647369       0    Inf
## col=3 véhicules et plus        53.89949  16.239487 12.856476       0    Inf
## atm=Normale                    52.69750 100.000000 80.973765       0    Inf
## lum=Plein jour                 45.11035  72.422158 68.506153       0    Inf
## catv=VU seul                   58.32360   7.553534  5.526373       0    Inf
## catv=VL seul                   59.64556  92.357142 66.073407       0    Inf
## secu1=Voiture                  63.06923  88.552309 59.912396       0    Inf
## 
## $`2`
##                       Cla/Mod    Mod/Cla     Global p.value v.test
## situ=Sur accotement  22.71899  17.326410 12.9091720       0    Inf
## situ=Aucun           28.94769   8.655207  5.0610686       0    Inf
## infra=Non            18.72060  96.170742 86.9564855       0    Inf
## surf=Normale         20.77258  95.514895 77.8322322       0    Inf
## catr=Voie Communale  19.91664  53.034983 45.0738988       0    Inf
## atm=Normale          20.90424 100.000000 80.9737647       0    Inf
## agg=En agglomération 18.89943  69.244115 62.0173042       0    Inf
## catv=Poids lourd     65.87258   7.417342  1.9059977       0    Inf
## catv=Engin agricole  67.33443   3.515486  0.8837448       0    Inf
## catv=Bus             67.70261   6.218853  1.5548326       0    Inf
## 
## $`3`
##                                 Cla/Mod     Mod/Cla     Global       p.value
## infra=Oui                     100.00000 100.0000000 11.0015080  0.000000e+00
## circ=A sens unique             14.88799  23.8943582 17.6567746  0.000000e+00
## intersection=Intersection      16.69103  40.8557365 26.9291171  0.000000e+00
## intersection=Giratoire         35.50220   9.9375237  3.0794641  0.000000e+00
## col=2 véhicules - par le côté  14.07988  37.0011359 28.9113464  0.000000e+00
## intersection=Passage à niveau  56.04900   0.6929193  0.1360088 2.080035e-173
## catr=Autoroute                 14.67621  14.4850435 10.8582093 1.426839e-164
## catv=Tramway                   50.79365   0.7269973  0.1574619 5.935163e-162
## plan=Non Rectiligne            13.85087  20.0208254 15.9021986 6.780154e-157
## circ=A chaussées séparées      13.73074  19.4055282 15.5483258 1.293665e-140
##                                 v.test
## infra=Oui                          Inf
## circ=A sens unique                 Inf
## intersection=Intersection          Inf
## intersection=Giratoire             Inf
## col=2 véhicules - par le côté      Inf
## intersection=Passage à niveau 28.07322
## catr=Autoroute                27.33983
## catv=Tramway                  27.11865
## plan=Non Rectiligne           26.68635
## circ=A chaussées séparées     25.24474
## 
## $`4`
##                                Cla/Mod   Mod/Cla    Global p.value v.test
## classe_age=15-24 ans          16.44619  29.46895 20.767273       0    Inf
## gr_dep=plus de 2 M hab        16.90813  30.51667 20.918070       0    Inf
## situ=Sur chaussée             14.31764  95.56294 77.356722       0    Inf
## infra=Non                     13.32840 100.00000 86.956486       0    Inf
## catr=Voie Communale           13.87293  53.95274 45.073899       0    Inf
## col=Sans collision            23.84194  11.89505  5.782353       0    Inf
## col=2 véhicules - par le côté 16.96516  42.32006 28.911346       0    Inf
## agg=En agglomération          13.52085  72.34972 62.017304       0    Inf
## catv=2 roues motorisé         60.48932  99.97125 19.154746       0    Inf
## secu1=Deux roues              61.73568  97.01860 18.213723       0    Inf
## 
## $`5`
##                                  Cla/Mod   Mod/Cla    Global p.value v.test
## situ=Autre/Non Renseigné       22.222222  4.999880  1.951403       0    Inf
## infra=Non Renseigné            23.378213  5.504191  2.042007       0    Inf
## infra=Non                       9.425091 94.495809 86.956486       0    Inf
## surf=Anormale                  36.315537 76.482313 18.266002       0    Inf
## plan=Rectiligne                10.881902 94.858433 75.604229       0    Inf
## circ=A chaussées séparées      13.765573 24.677601 15.548326       0    Inf
## catr=Autoroute                 15.301542 19.156600 10.858209       0    Inf
## mois_acc=décembre              15.135269 14.644221  8.391722       0    Inf
## mois_acc=janvier               17.323270 15.047669  7.533804       0    Inf
## intersection=Hors intersection 11.311429 89.529550 68.647369       0    Inf
## 
## $`6`
##                            Cla/Mod    Mod/Cla    Global p.value v.test
## infra=Non                 10.50799 100.000000 86.956486       0    Inf
## surf=Anormale             39.86636  79.694552 18.266002       0    Inf
## plan=Non Rectiligne       23.54844  40.982448 15.902199       0    Inf
## mois_acc=janvier          17.93149  14.784591  7.533804       0    Inf
## intersection=Intersection 12.42391  36.614999 26.929117       0    Inf
## col=Autre collision       12.67181  39.067700 28.170900       0    Inf
## atm=Temps éblouissant     36.94989   5.798951  1.434028       0    Inf
## atm=Temps couvert         40.12189  13.355368  3.041557       0    Inf
## atm=Pluie légère          40.28580  45.304308 10.275642       0    Inf
## atm=Pluie forte           39.52242   9.582858  2.215506       0    Inf</code></pre>
<div id="classe-1-177-478" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-1-177-478" class="anchor"></a>Classe 1 (177 478)</h3>
<p>accident en plein jour avec des conditions météo normales, sur une route “plate”, rectiligne sans pb sur la surface sur-représentation des autoroutes, hors intersection avec une collisions de 3 véhicules ou plus</p>
</div>
<div id="classe-2-70-517" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-2-70-517" class="anchor"></a>Classe 2 (70 517)</h3>
<p>très peu d’info sur le lieu et les conditions (modalités à autres ou non renseigné) route départementale</p>
</div>
<div id="classe-3-48-762" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-3-48-762" class="anchor"></a>Classe 3 (48 762)</h3>
<p>voiture + collision de 2 véhicules route à sens unique avec une infrastructure à une intersection/giratoire</p>
</div>
<div id="classe-4-88-249" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-4-88-249" class="anchor"></a>Classe 4 (88 249)</h3>
<p>durant l’hiver (nov, dec ou janv) conditions météo dégradées (vent/tempête, couvert ou pluie) + surface de la route anormale + absence d’infrastructure</p>
</div>
<div id="classe-5-25-154" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-5-25-154" class="anchor"></a>Classe 5 (25 154)</h3>
<p>âges extrèmes (avant 15 ans ou 75 ans et +) accident sur une voie communale, en agglo + autre collision + pluie légère</p>
</div>
<div id="classe-6-69-956" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-6-69-956" class="anchor"></a>Classe 6 (69 956)</h3>
<p>usagers âgés entre 15 et 24 ans + département de plus de 2 millions d’habitants voie communale + en agglo + sans infrastructure + surface de la route normale</p>
</div>
</div>
</div>
<div id="k-modes" class="section level1">
<h1 class="hasAnchor">
<a href="#k-modes" class="anchor"></a>K-modes</h1>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod_kmodes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/klaR/man/kmodes.html">kmodes</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="va">base</span><span class="op">)</span>, <span class="fl">6</span><span class="op">)</span> <span class="co"># on prend 6 classes comme ce que la classification a trouvé</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod_kmodes</span><span class="op">)</span></code></pre></div>
<pre><code>##            Length Class      Mode   
## cluster    480116 -none-     numeric
## size            6 table      numeric
## modes          22 data.frame list   
## withindiff      6 -none-     numeric
## iterations      1 -none-     numeric
## weighted        1 -none-     logical</code></pre>
<div id="pour-voir-la-modalité-de-chaque-variables-la-plus-présente-dans-chaque-classe" class="section level2">
<h2 class="hasAnchor">
<a href="#pour-voir-la-modalit%C3%A9-de-chaque-variables-la-plus-pr%C3%A9sente-dans-chaque-classe" class="anchor"></a>Pour voir la modalité de chaque variables la plus présente dans chaque classe</h2>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod_kmodes</span><span class="op">$</span><span class="va">modes</span></code></pre></div>
<pre><code>##         catu         grav     sexe      secu1             catv
## 1 Conducteur      Indemne Masculin    Voiture          VL seul
## 2 Conducteur      Indemne Masculin    Voiture          VL seul
## 3 Conducteur      Indemne Masculin    Voiture          VL seul
## 4 Conducteur Blessé léger Masculin    Voiture          VL seul
## 5   Passager Blessé léger Masculin    Voiture          VL seul
## 6 Conducteur Blessé léger Masculin Deux roues 2 roues motorisé
##                          lum                agg     atm
## 1                 Plein jour   En agglomération Normale
## 2                 Plein jour Hors agglomération Normale
## 3 Nuit avec éclairage public   En agglomération Normale
## 4                 Plein jour Hors agglomération Normale
## 5                 Plein jour Hors agglomération Normale
## 6                 Plein jour   En agglomération Normale
##                           col      intersection mois_acc jour_acc
## 1             Autre collision Hors intersection     mars    jeudi
## 2      2 véhicules - frontale Hors intersection     août    mardi
## 3   2 véhicules - par le côté      Intersection  février vendredi
## 4 2 véhicules - par l'arrière Hors intersection novembre   samedi
## 5         3 véhicules et plus Hors intersection      mai mercredi
## 6   2 véhicules - par le côté Hors intersection novembre   samedi
##                   catr                 circ prof       plan    surf infra
## 1       Voie Communale     Bidirectionnelle Plat Rectiligne Normale   Non
## 2 Route Départementale     Bidirectionnelle Plat Rectiligne Normale   Non
## 3       Voie Communale     Bidirectionnelle Plat Rectiligne Normale   Non
## 4            Autoroute A chaussées séparées Plat Rectiligne Normale   Non
## 5            Autoroute A chaussées séparées Plat Rectiligne Normale   Non
## 6       Voie Communale     Bidirectionnelle Plat Rectiligne Normale   Non
##           situ                    gr_dep classe_age cl_heure
## 1 Sur chaussée 1 000 000 - 2 000 000 hab  25-34 ans  10h-15h
## 2 Sur chaussée   500 000 - 1 000 000 hab  15-24 ans  16h-19h
## 3 Sur chaussée           plus de 2 M hab  15-24 ans  20h-06h
## 4 Sur chaussée 1 000 000 - 2 000 000 hab  25-34 ans   7h-10h
## 5 Sur chaussée 1 000 000 - 2 000 000 hab  35-44 ans   7h-10h
## 6 Sur chaussée 1 000 000 - 2 000 000 hab  15-24 ans  16h-19h</code></pre>
<div id="classe-1" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-1" class="anchor"></a>Classe 1</h3>
<p>blessé léger + conducteur + hommes + 15-24 ans + depmt entre 1 et 2 millions d’hab mardi + mars + 16h-19h 2 roues + nuit avec éclairage + en agglo + hors intersection + voie communale bidirectionnelle</p>
</div>
<div id="classe-2" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-2" class="anchor"></a>Classe 2</h3>
<p>blessé léger + conducteur + hommes + 35-44 ans + depmt entre 1 et 2 millions d’hab jeudi + septembre + 10h-15h voiture + plein jour + en agglo + hors intersection + voie communale bidirectionnelle</p>
</div>
<div id="classe-3" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-3" class="anchor"></a>Classe 3</h3>
<p>indemne + conducteur + femme + 45-54 ans + depmt entre 1 et 2 millions d’hab mardi + juillet + 16h-19h voiture + plein jour + en agglo + hors intersection + voie communale bidirectionnelle</p>
</div>
<div id="classe-4" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-4" class="anchor"></a>Classe 4</h3>
<p>blessé hospitalisé + conducteur + hommes + 25-34 ans + depmt de moins de 500 000 hab samedi + juillet + 20h-06h voiture + nuit sans éclairage + hors agglo + hors intersection + route départementale birectionnelle</p>
</div>
<div id="classe-5" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-5" class="anchor"></a>Classe 5</h3>
<p>blessé léger + conducteur + hommes + 35-44 ans + depmt de 2 millions et plus d’hab samedi + juin + 16h-19h 2 roues + plein jour + en agglo + à une intersection + voie communale à sens unique</p>
</div>
<div id="classe-6" class="section level3">
<h3 class="hasAnchor">
<a href="#classe-6" class="anchor"></a>Classe 6</h3>
<p>blessé hospitalisé + conducteur + hommes + 15-24 ans + depmt de 2 millions et plus d’hab mardi + août + 16h-19h 2 roues + plein jour + en agglo + à une intersection + voie communale bidirectionnelle</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Alexandre Atthar, Cecile Simon, Coralie Bos.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
